#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QList>
#include "Settings.h"

class View;
class DataBinding;

namespace Ui {
    class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

public slots:
    // Used internally to keep data bindings and settings in sync.
    void settingsChanged();

protected:
    // Overridden from QWidget
    void closeEvent(QCloseEvent *event);

private:
    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;
    QList<DataBinding *> m_bindings;
    View *view;

    void dataBind();
};

#endif // MAINWINDOW_H
